image=imread('LocalEnh.bmp');
Mat=double(image);
M=mean2(Mat);
Var=std2 (Mat);
winSize=[3 3];
K0=0.4;
K1=0.02;
K2=0.4;
E=4; 
newImage=nlfilter(Mat,winSize,@LocalStat,K0,K1,K2,E,M,Var);
EnhImage=im2uint8(mat2gray(newImage));
imshow (EnhImage);
